version: 2

sources:
  - name: jaffle_shop
    description: This is a replica of the Postgres database used by our app
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: One record per customer
      - name: orders
        description: One record per order. Includes cancelled and deleted orders also.
  - name: stripe
    description: This is where the payment data comes from
    database: raw
    schema: stripe
    tables:
      - name: PAYMENT
        description: One record per payment, One order could contain different payments
